# justfile for crustimg
#
# To use this file, you need to have `just` installed:
# cargo install just
#
# Run `just` with no arguments (or `just help`) for a list of available commands.

# Define the release binary path for convenience.
CRUSTIMG := "./target/release/crustimg"

# --- Default Command ---

# This recipe runs if `just` is invoked without any arguments.
# It simply calls the `help` recipe to list available commands.
default:
    just help

# --- Help Command ---

# Displays a list of all available 'just' commands.
# This uses 'just --list' which is dynamically generated by 'just'.
help:
    @just --list

# --- Setup Commands ---

# Creates a dummy image and an output directory for testing.
# Requires 'convert' (ImageMagick) to be installed for the dummy image creation.
setup:
    @echo "Setting up test environment..."
    mkdir -p images
    mkdir -p output
    @if ! [ -f images/test-image.jpg ]; then \
        echo "Creating a dummy test image (requires ImageMagick's 'convert')..."; \
        convert -size 400x300 gradient:red-blue images/test-image.jpg; \
    else \
        echo "Dummy image 'images/test-image.jpg' already exists."; \
    fi
    @echo "Test environment ready."

# --- Build Command ---

# Builds the Rust project in release mode.
build:
    @echo "Building crustimg"
    cargo build
    @echo "Build complete."

release: build
    @echo "Building crustimg in release mode..."
    cargo build --release
    @echo "Build complete."

# --- Run Commands ---

# Views an image in the terminal using viuer.
# Usage: just view <IMAGE_PATH>
view IMAGE_PATH: build
    @echo "Viewing '{{IMAGE_PATH}}'..."
    $(CRUSTIMG) "{{IMAGE_PATH}}"

# Strips EXIF data from an image and saves it to a new file, then displays the output.
# Saves to 'output/<original_name>-stripped.jpg' by default.
# Usage: just strip <INPUT_PATH> [OUTPUT_DIR]
strip INPUT_PATH OUTPUT_DIR="output": build
    @echo "Stripping EXIF data from '{{INPUT_PATH}}' and saving to '{{OUTPUT_DIR}}'..."
    $(CRUSTIMG) "{{INPUT_PATH}}" --strip-exif --output "{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-stripped.jpg"
    @echo "Output saved to '{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-stripped.jpg'"

# Shrinks an image to a JPEG and saves it to a new file, then displays the output.
# Saves to 'output/<original_name>-shrunk.jpg' by default.
# Usage: just shrink <INPUT_PATH> [OUTPUT_DIR]
shrink INPUT_PATH OUTPUT_DIR="output": build
    @echo "Shrinking '{{INPUT_PATH}}' and saving to '{{OUTPUT_DIR}}'..."
    $(CRUSTIMG) "{{INPUT_PATH}}" --shrink --output "{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-shrunk.jpg"
    @echo "Output saved to '{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-shrunk.jpg'"

# Applies both strip and shrink operations, saves to a new file, then displays the output.
# Saves to 'output/<original_name>-processed.jpg' by default.
# Usage: just process <INPUT_PATH> [OUTPUT_DIR]
process INPUT_PATH OUTPUT_DIR="output": build
    @echo "Processing '{{INPUT_PATH}}' (strip EXIF, shrink) and saving to '{{OUTPUT_DIR}}'..."
    $(CRUSTIMG) "{{INPUT_PATH}}" --strip-exif --shrink --output "{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-processed.jpg"
    @echo "Output saved to '{{OUTPUT_DIR}}/$(shell basename "{{INPUT_PATH}}" .jpg)-processed.jpg'"

# --- Clean Command ---

# Removes build artifacts and all generated output/image files.
clean:
    @echo "Cleaning build artifacts and all generated files..."
    cargo clean
    # rm -rf output images
    @echo "Clean complete."
